language: php
php:
- 7.3
- 7.4
matrix:
  include:
    - php: 7.3
      script:
      - phpdbg -qrr ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
      after_script:
      - php ./vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
before_script:
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-dist
script:
- vendor/bin/phpunit
