# Usefull links
# =============
# https://hub.docker.com/_/php/
# https://docs.docker.com/compose/overview/
# https://docs.docker.com/compose/compose-file/
#
# Usefull commands
# ================
#
# Start containers
# $ docker-compose up -d
#
# View running containers
# $ docker-compose ps
#
# Connect into command line of running container
# $ docker-compose run <container_name> bash
# where <name> could be db_passport, etc.
# Tip: `Ctrl+p` + `Ctrl+q` + `Enter` (to exit container bash)
#
# Stop containers
# $ docker-compose down
#
# Remove images
# $ docker rmi db_passport
#
# Run non-default docker-compose file
# $ docker-compose -f <file_name.yml> up -d
# $ docker-compose -f <file_name.yml> down
# $ docker-compose -f <file_name.yml> stop

version: '3'
services:
  db_postgres:
    image: postgres
    container_name: db_passport_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: passport
      POSTGRES_DB: passport
      POSTGRES_PASSWORD: secret

  db_percona:
    image: percona
    container_name: db_passport_percona
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: passport
      MYSQL_DATABASE: passport
      MYSQL_PASSWORD: secret
#
#cli_7_1_php:
#  build: ./../../docker/7_1_cli
#  container_name: cli_7_1_php_limoncello
#  volumes:
#    - .:/app
#  working_dir: /app
#  tty: true
#
#cli_7_2_php:
#  build: ./../../docker/7_2_cli
#  container_name: cli_7_2_php_limoncello
#  volumes:
#    - .:/app
#  working_dir: /app
#  tty: true
#
#cli_7_4_php:
#    build: ./../../docker/7_4_cli
#    container_name: cli_7_4_php_limoncello
#    volumes:
#        - .:/app
#    working_dir: /app
#    tty: true
#
#cli_hhvm:
#  image: hhvm/hhvm
#  container_name: cli_hhvm_limoncello
#  volumes:
#    - .:/app
#  working_dir: /app
#  tty: true
